logging:
    level:
        org:
            springframework: INFO
        com:
            sap:
                olingo: DEBUG
odata:
    api:
        version: "0.1.0-alpha.1"
        path_prefix: "v1"
    jpa:
        punit_name: "com.alvachien.libraryapi" # used in persistance.xml for Java EE, but in Spring (like here) only used as namespace of the OData service
        request_mapping_path: "apis/${odata.api.path_prefix}"
        root_packages: "com.alvachien.libraryapi"
static:
    api:
        version: "0.1.0-alpha.1"
        path_prefix: "v1"
    request_mapping_path: "apis/${static.api.path_prefix}"
server:
    port: 9010
    default_response_type: json
spring:
    autoconfigure:
        exclude:
            - org.springframework.boot.actuate.autoconfigure.metrics.orm.jpa.HibernateMetricsAutoConfiguration
    datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: jdbc:sqlserver://localhost;database=library;integratedSecurity=true;encrypt=true;trustServerCertificate=true
        hikari:
            minimumIdle: 1
            idleTimeout: 60000
            maximumPoolSize: 5
    servlet:
        multipart:
            enabled: false
        jpa:
            show-sql: true

